apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ping-pong

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - namespace.yaml
  - pdb.yaml

images:
  - name: ghcr.io/thedin87/echo-pong
    newTag: latest
